-- CREATE DATABASE PROJETO;
USE PROJETO;

-- ============================================================================
-- 1. TABELAS INDEPENDENTES / BASE
-- ============================================================================

CREATE TABLE PESSOA (
    id INT AUTO_INCREMENT,
    nome VARCHAR(150) NOT NULL,
    sexo CHAR(1),
    data_nascimento DATE NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    CONSTRAINT PK_PESSOA PRIMARY KEY (id)
);

CREATE TABLE PREDIO (
    id INT AUTO_INCREMENT,
    quadra VARCHAR(20),
    numero VARCHAR(20),
    bairro VARCHAR(50),
    estado CHAR(2) DEFAULT 'DF',
    conjunto VARCHAR(20),
    ql VARCHAR(20),
    cidade VARCHAR(50),
    CONSTRAINT PK_PREDIO PRIMARY KEY (id)
);

CREATE TABLE SEMESTRE (
    id INT AUTO_INCREMENT,
    codigo VARCHAR(10) NOT NULL UNIQUE, -- Ex: '2026.1'
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    CONSTRAINT PK_SEMESTRE PRIMARY KEY (id)
);

CREATE TABLE ESCOLARIDADE (
    id INT AUTO_INCREMENT,
    nivel VARCHAR(50) NOT NULL, -- Ex: 'Mestrado', 'Doutorado'
    CONSTRAINT PK_ESCOLARIDADE PRIMARY KEY (id)
);

CREATE TABLE ATIVIDADE (
    id INT AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    data_hora_inicio DATETIME NOT NULL,
    data_hora_fim DATETIME NOT NULL,
    CONSTRAINT PK_ATIVIDADE PRIMARY KEY (id)
);

-- ============================================================================
-- 2. INFRAESTRUTURA ADMINISTRATIVA (UNIVERSIDADE, DIREÇÃO, DEPARTAMENTO)
-- ============================================================================

CREATE TABLE DIRETOR (
    id INT AUTO_INCREMENT,
    idPROFESSOR INT NOT NULL, -- FK será adicionada no fim por dependência cíclica
    data_posse DATE NOT NULL,
    data_exoneracao DATE NULL,
    status VARCHAR(20) DEFAULT 'Ativo',
    CONSTRAINT PK_DIRETOR PRIMARY KEY (id)
);

CREATE TABLE VICE_DIRETOR (
    id INT AUTO_INCREMENT,
    idPROFESSOR INT NOT NULL, -- FK será adicionada no fim
    data_posse DATE NOT NULL,
    data_exoneracao DATE NULL,
    status VARCHAR(20) DEFAULT 'Ativo',
    CONSTRAINT PK_VICE_DIRETOR PRIMARY KEY (id)
);

CREATE TABLE DIRECAO (
    id INT AUTO_INCREMENT,
    idDIRETOR INT NULL,
    idVICE_DIRETOR INT NULL,
    CONSTRAINT PK_DIRECAO PRIMARY KEY (id),
    CONSTRAINT FK_DIRECAO_DIRETOR FOREIGN KEY (idDIRETOR) REFERENCES DIRETOR (id) ON DELETE SET NULL,
    CONSTRAINT FK_DIRECAO_VICE FOREIGN KEY (idVICE_DIRETOR) REFERENCES VICE_DIRETOR (id) ON DELETE SET NULL
);

CREATE TABLE REITOR (
    id INT AUTO_INCREMENT,
    idPROFESSOR INT NOT NULL, -- FK será adicionada no fim
    data_posse DATE NOT NULL,
    data_exoneracao DATE NULL,
    status VARCHAR(20) DEFAULT 'Ativo',
    CONSTRAINT PK_REITOR PRIMARY KEY (id)
);

CREATE TABLE UNIVERSIDADE (
    id INT AUTO_INCREMENT,
    idREITOR INT NULL,
    nome VARCHAR(100) NOT NULL,
    data_fundacao DATE,
    CONSTRAINT PK_UNIVERSIDADE PRIMARY KEY (id),
    CONSTRAINT FK_UNIVERSIDADE_REITOR FOREIGN KEY (idREITOR) REFERENCES REITOR (id) ON DELETE SET NULL
);

CREATE TABLE DEPARTAMENTO (
    id INT AUTO_INCREMENT,
    idDIRECAO INT NULL,
    idUNIVERSIDADE INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (id),
    CONSTRAINT FK_DEPARTAMENTO_DIRECAO FOREIGN KEY (idDIRECAO) REFERENCES DIRECAO (id) ON DELETE SET NULL,
    CONSTRAINT FK_DEPARTAMENTO_UNI FOREIGN KEY (idUNIVERSIDADE) REFERENCES UNIVERSIDADE (id) ON DELETE CASCADE
);

-- ============================================================================
-- 3. RECURSOS HUMANOS E QUALIFICAÇÃO (PROFESSOR, CONTA, FORMAÇÃO)
-- ============================================================================

CREATE TABLE PROFESSOR (
    id INT NOT NULL, -- ID vindo de Pessoa (Herança)
    idDEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (id),
    CONSTRAINT FK_PROFESSOR_PESSOA FOREIGN KEY (id) REFERENCES PESSOA (id) ON DELETE CASCADE,
    CONSTRAINT FK_PROFESSOR_DEP FOREIGN KEY (idDEPARTAMENTO) REFERENCES DEPARTAMENTO (id)
);

CREATE TABLE FORMACAO (
    id INT AUTO_INCREMENT,
    idESCOLARIDADE INT NOT NULL,
    instituicao VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    data_conclusao DATE,
    registro_no_mec VARCHAR(50),
    CONSTRAINT PK_FORMACAO PRIMARY KEY (id),
    CONSTRAINT FK_FORMACAO_ESC FOREIGN KEY (idESCOLARIDADE) REFERENCES ESCOLARIDADE (id)
);

-- ============================================================================
-- 4. CURSOS, ACADÊMICO E VÍNCULOS DE MATRÍCULA
-- ============================================================================

CREATE TABLE CURSO (
    id INT AUTO_INCREMENT,
    idDEPARTAMENTO INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (id),
    CONSTRAINT FK_CURSO_DEP FOREIGN KEY (idDEPARTAMENTO) REFERENCES DEPARTAMENTO (id)
);

CREATE TABLE CONTA (
    id INT AUTO_INCREMENT,
    tipo VARCHAR(20) NOT NULL, -- 'ALUNO' ou 'PROFESSOR'
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    idPROFESSOR INT NULL,
    idMATRICULA_CURSO INT NULL, -- FK será amarrada após criação da MATRICULA_CURSO
    CONSTRAINT PK_CONTA PRIMARY KEY (id),
    CONSTRAINT FK_CONTA_PROFESSOR FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id) ON DELETE CASCADE
);

CREATE TABLE MATRICULA_CURSO (
    id INT AUTO_INCREMENT,
    idPESSOA INT NOT NULL,
    idCONTA INT NULL,
    idCURSO INT NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE, -- Número da Matrícula Geral
    data_matricula DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'Ativo',
    data_trancamento DATE NULL,
    CONSTRAINT PK_MATRICULA_CURSO PRIMARY KEY (id),
    CONSTRAINT FK_MAT_CURSO_PESSOA FOREIGN KEY (idPESSOA) REFERENCES PESSOA (id) ON DELETE CASCADE,
    CONSTRAINT FK_MAT_CURSO_CONTA FOREIGN KEY (idCONTA) REFERENCES CONTA (id) ON DELETE SET NULL,
    CONSTRAINT FK_MAT_CURSO_CURSO FOREIGN KEY (idCURSO) REFERENCES CURSO (id)
);

-- Agora que MATRICULA_CURSO existe, adicionamos a FK na CONTA que faltava
ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_MATRICULA 
FOREIGN KEY (idMATRICULA_CURSO) REFERENCES MATRICULA_CURSO (id) ON DELETE CASCADE;

CREATE TABLE ALUNO (
    id INT NOT NULL, -- ID vindo de Pessoa (Herança)
    idMATRICULA_CURSO INT NULL,
    CONSTRAINT PK_ALUNO PRIMARY KEY (id),
    CONSTRAINT FK_ALUNO_PESSOA FOREIGN KEY (id) REFERENCES PESSOA (id) ON DELETE CASCADE,
    CONSTRAINT FK_ALUNO_MAT_CURSO FOREIGN KEY (idMATRICULA_CURSO) REFERENCES MATRICULA_CURSO (id) ON DELETE SET NULL
);

CREATE TABLE DISCIPLINA (
    id INT AUTO_INCREMENT,
    idCURSO INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE, -- Ex: 'CIC0004'
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (id),
    CONSTRAINT FK_DISCIPLINA_CURSO FOREIGN KEY (idCURSO) REFERENCES CURSO (id) ON DELETE CASCADE
);

CREATE TABLE TURMA (
    id INT AUTO_INCREMENT,
    idDISCIPLINA INT NOT NULL,
    idPROFESSOR INT NOT NULL,
    quantidade INT NOT NULL,
    CONSTRAINT PK_TURMA PRIMARY KEY (id),
    CONSTRAINT FK_TURMA_DISCIPLINA FOREIGN KEY (idDISCIPLINA) REFERENCES DISCIPLINA (id),
    CONSTRAINT FK_TURMA_PROFESSOR FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id)
);

CREATE TABLE MATRICULA_DISCIPLINA (
    id INT AUTO_INCREMENT,
    idALUNO INT NOT NULL,
    idDISCIPLINA INT NOT NULL,
    idTURMA INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    data_matricula DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'Matriculado',
    data_trancamento DATE NULL,
    CONSTRAINT PK_MATRICULA_DISCIPLINA PRIMARY KEY (id),
    CONSTRAINT FK_MAT_DISC_ALUNO FOREIGN KEY (idALUNO) REFERENCES ALUNO (id) ON DELETE CASCADE,
    CONSTRAINT FK_MAT_DISC_DISC FOREIGN KEY (idDISCIPLINA) REFERENCES DISCIPLINA (id),
    CONSTRAINT FK_MAT_DISC_TURMA FOREIGN KEY (idTURMA) REFERENCES TURMA (id)
);

-- ============================================================================
-- 5. ROTINA SEMESTRAL (NOTAS, AULAS, FREQUÊNCIA, INFRA)
-- ============================================================================

CREATE TABLE NOTA (
    id INT AUTO_INCREMENT,
    idMATRICULA_DISCIPLINA INT NOT NULL,
    idATIVIDADE INT NOT NULL,
    valor DECIMAL(4,2) NOT NULL, -- Armazena notas de 0.00 a 10.00
    CONSTRAINT PK_NOTA PRIMARY KEY (id),
    CONSTRAINT FK_NOTA_MAT_DISC FOREIGN KEY (idMATRICULA_DISCIPLINA) REFERENCES MATRICULA_DISCIPLINA (id) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_ATIVIDADE FOREIGN KEY (idATIVIDADE) REFERENCES ATIVIDADE (id)
);

CREATE TABLE AULA (
    id INT AUTO_INCREMENT,
    idTURMA INT NOT NULL,
    idPROFESSOR INT NOT NULL,
    data DATE NOT NULL,
    horario_inicia TIME NOT NULL,
    horario_termina TIME NOT NULL,
    CONSTRAINT PK_AULA PRIMARY KEY (id),
    CONSTRAINT FK_AULA_TURMA FOREIGN KEY (idTURMA) REFERENCES TURMA (id) ON DELETE CASCADE,
    CONSTRAINT FK_AULA_PROFESSOR FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id)
);

CREATE TABLE FREQUENCIA (
    id INT AUTO_INCREMENT,
    idAULA INT NOT NULL,
    data_aula DATE NOT NULL,
    presenca BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_FREQUENCIA PRIMARY KEY (id),
    CONSTRAINT FK_FREQUENCIA_AULA FOREIGN KEY (idAULA) REFERENCES AULA (id) ON DELETE CASCADE
);

CREATE TABLE SALA (
    id INT AUTO_INCREMENT,
    idPREDIO INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    quantidade INT NOT NULL, -- Capacidade corrigida de 'quatidade'
    CONSTRAINT PK_SALA PRIMARY KEY (id),
    CONSTRAINT FK_SALA_PREDIO FOREIGN KEY (idPREDIO) REFERENCES PREDIO (id) ON DELETE CASCADE
);

CREATE TABLE DISPONIBILIDADE (
    id INT AUTO_INCREMENT,
    idSALA INT NOT NULL,
    data DATE NOT NULL,
    hora_abertura TIME NOT NULL,
    hora_fechamento TIME NOT NULL,
    status BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_DISPONIBILIDADE PRIMARY KEY (id),
    CONSTRAINT FK_DISPONIBILIDADE_SALA FOREIGN KEY (idSALA) REFERENCES SALA (id) ON DELETE CASCADE
);

-- ============================================================================
-- 6. TABELAS ASSOCIATIVAS (RELACIONAMENTOS N:M)
-- ============================================================================

CREATE TABLE INTERAGE (
    idTURMA INT NOT NULL,
    idDISPONIBILIDADE INT NOT NULL,
    CONSTRAINT PK_INTERAGE PRIMARY KEY (idTURMA, idDISPONIBILIDADE),
    CONSTRAINT FK_INTERAGE_TURMA FOREIGN KEY (idTURMA) REFERENCES TURMA (id) ON DELETE CASCADE,
    CONSTRAINT FK_INTERAGE_DISPO FOREIGN KEY (idDISPONIBILIDADE) REFERENCES DISPONIBILIDADE (id) ON DELETE CASCADE
);

CREATE TABLE POSSUI (
    idSEMESTRE INT NOT NULL,
    idDISCIPLINA INT NOT NULL,
    CONSTRAINT PK_POSSUI PRIMARY KEY (idSEMESTRE, idDISCIPLINA),
    CONSTRAINT FK_POSSUI_SEMESTRE FOREIGN KEY (idSEMESTRE) REFERENCES SEMESTRE (id) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI_DISCIPLINA FOREIGN KEY (idDISCIPLINA) REFERENCES DISCIPLINA (id) ON DELETE CASCADE
);

CREATE TABLE POSSUI1 (
    idFORMACAO INT NOT NULL,
    idPROFESSOR INT NOT NULL,
    CONSTRAINT PK_POSSUI1 PRIMARY KEY (idFORMACAO, idPROFESSOR),
    CONSTRAINT FK_POSSUI1_FORMACAO FOREIGN KEY (idFORMACAO) REFERENCES FORMACAO (id) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI1_PROFESSOR FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id) ON DELETE CASCADE
);

CREATE TABLE POSSUI2 (
    idAULA INT NOT NULL,
    idATIVIDADE INT NOT NULL,
    CONSTRAINT PK_POSSUI2 PRIMARY KEY (idAULA, idATIVIDADE),
    CONSTRAINT FK_POSSUI2_AULA FOREIGN KEY (idAULA) REFERENCES AULA (id) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI2_ATIVIDADE FOREIGN KEY (idATIVIDADE) REFERENCES ATIVIDADE (id) ON DELETE CASCADE
);

CREATE TABLE POSSUI3 (
    idMATRICULA_DISCIPLINA INT NOT NULL,
    idFREQUENCIA INT NOT NULL,
    CONSTRAINT PK_POSSUI3 PRIMARY KEY (idMATRICULA_DISCIPLINA, idFREQUENCIA),
    CONSTRAINT FK_POSSUI3_MAT_DISC FOREIGN KEY (idMATRICULA_DISCIPLINA) REFERENCES MATRICULA_DISCIPLINA (id) ON DELETE CASCADE,
    CONSTRAINT FK_POSSUI3_FREQ FOREIGN KEY (idFREQUENCIA) REFERENCES FREQUENCIA (id) ON DELETE CASCADE
);

CREATE TABLE REALIZA (
    idMATRICULA_DISCIPLINA INT NOT NULL,
    idATIVIDADE INT NOT NULL,
    CONSTRAINT PK_REALIZA PRIMARY KEY (idMATRICULA_DISCIPLINA, idATIVIDADE),
    CONSTRAINT FK_REALIZA_MAT_DISC FOREIGN KEY (idMATRICULA_DISCIPLINA) REFERENCES MATRICULA_DISCIPLINA (id) ON DELETE CASCADE,
    CONSTRAINT FK_REALIZA_ATIVIDADE FOREIGN KEY (idATIVIDADE) REFERENCES ATIVIDADE (id) ON DELETE CASCADE
);

CREATE TABLE MINISTRA (
    idPROFESSOR INT NOT NULL,
    idDISCIPLINA INT NOT NULL,
    CONSTRAINT PK_MINISTRA PRIMARY KEY (idPROFESSOR, idDISCIPLINA),
    CONSTRAINT FK_MINISTRA_PROFESSOR FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id) ON DELETE CASCADE,
    CONSTRAINT FK_MINISTRA_DISCIPLINA FOREIGN KEY (idDISCIPLINA) REFERENCES DISCIPLINA (id) ON DELETE CASCADE
);

-- ============================================================================
-- 7. CHAVES ESTRANGEIRAS ATRASADAS (RESOLVENDO DEPENDÊNCIAS CÍCLICAS)
-- ============================================================================

ALTER TABLE DIRETOR ADD CONSTRAINT FK_DIRETOR_PROFESSOR 
FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id);

ALTER TABLE VICE_DIRETOR ADD CONSTRAINT FK_VICE_PROFESSOR 
FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id);

ALTER TABLE REITOR ADD CONSTRAINT FK_REITOR_PROFESSOR 
FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR (id);